M48
; DRILL file KiCad 10.0.3 date 2026-08-31T03:10:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-31T03:10:59+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X116.504Y-162.016
X122.284Y-162.016
T2
X147.639Y-157.16
M30
